name: RDC3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - jupyter_contrib_nbextensions
  - lmfit
  - matplotlib
  - mpld3
  - nb_conda_kernels
  - numpy
  - scipy  